<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24070" started-at="2015-11-29T08:00:47Z" finished-at="2015-11-29T08:01:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24070" started-at="2015-11-29T08:00:47Z" finished-at="2015-11-29T08:01:11Z">
      <class name="com.testcases.LoginTestCases">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.testcases.LoginTestCases@c39f790]" name="beforeClass" is-config="true" duration-ms="19049" started-at="2015-11-29T13:30:47Z" finished-at="2015-11-29T13:31:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="checkBlankUserName(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginTestCases@c39f790]" name="checkBlankUserName" duration-ms="867" started-at="2015-11-29T13:31:06Z" data-provider="chkblankuname" finished-at="2015-11-29T13:31:07Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 3 parameters but the method com.testcases.LoginTestCases#checkBlankUserName takes 4 and TestNG is unable in inject a suitable object]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 3 parameters but the method com.testcases.LoginTestCases#checkBlankUserName takes 4 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1361)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1359)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkBlankUserName -->
        <test-method status="FAIL" signature="checkInvalidUserName(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginTestCases@c39f790]" name="checkInvalidUserName" duration-ms="31" started-at="2015-11-29T13:31:07Z" data-provider="logintestdata" finished-at="2015-11-29T13:31:07Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 3 parameters but the method com.testcases.LoginTestCases#checkInvalidUserName takes 4 and TestNG is unable in inject a suitable object]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 3 parameters but the method com.testcases.LoginTestCases#checkInvalidUserName takes 4 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1361)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1359)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkInvalidUserName -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testcases.LoginTestCases@c39f790]" name="beforeMethod" is-config="true" duration-ms="141" started-at="2015-11-29T13:31:07Z" finished-at="2015-11-29T13:31:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="checkCorrectUserName()[pri:0, instance:com.testcases.LoginTestCases@c39f790]" name="checkCorrectUserName" duration-ms="1979" started-at="2015-11-29T13:31:07Z" finished-at="2015-11-29T13:31:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkCorrectUserName -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.testcases.LoginTestCases@c39f790]" name="afterClass" is-config="true" duration-ms="1925" started-at="2015-11-29T13:31:09Z" finished-at="2015-11-29T13:31:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testcases.LoginTestCases@c39f790]" name="afterMethod" is-config="true" duration-ms="0" started-at="2015-11-29T13:31:09Z" finished-at="2015-11-29T13:31:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.testcases.LoginTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
